[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
IceFloeTracker = "04643c7a-9ac6-48c5-822f-2704f9e70bd3"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[sources]
IceFloeTracker = { path = "../" }

[compat]
Documenter = "1"
